//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Panderia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_receta
    {
        public int Id { get; set; }
        public decimal cantidad { get; set; }
        public int cabecera_recetaId { get; set; }
        public int articuloId { get; set; }
    
        public virtual articulo articulo { get; set; }
        public virtual cabecera_receta cabecera_receta { get; set; }
    }
}
